#!/usr/bin/env php
<?php
/**
 * PHP.Gt (http://php.gt)
 * @copyright Copyright Ⓒ 2014 Bright Flair Ltd. (http://brightflair.com)
 * @license Apache Version 2.0, January 2004. http://www.apache.org/licenses
 */
chdir(__DIR__);
chdir("..");

$seleniumVersion = "2.42";
$seleniumVersionFile = "2.42.2";
$seleniumFilename = "selenium.jar";
$seleniumRemoteFilename = "selenium-server-standalone-$seleniumVersionFile.jar";

if(!is_file($seleniumFilename)) {
	echo "Downloading Selenium...\n";
	copy("http://selenium-release.storage.googleapis.com/"
		. $seleniumVersion
		. "/"
		. $seleniumRemoteFilename,

		$seleniumFilename
	);
}

$bitSize = (PHP_INT_SIZE == 4)
	? 32
	: 64;

$chromeFilename = "chromedriver";
$chromeVersion = "2.9";
$os = strtolower(php_uname("s"));

if(!is_file($chromeFilename)) {
	echo "Downloading Chrome Driver...\n";
	copy("http://chromedriver.storage.googleapis.com/"
		. $chromeVersion
		. "/"
		. "chromedriver_"
		. $os
		. $bitSize
		. ".zip",

		$chromeFilename . ".zip"
	);
}
$zip = new ZipArchive();
$resource = $zip->open($chromeFilename . ".zip");
if(!$resource) {
	echo "Error unzipping chrome driver";
	exit(1);
}
$zip->extractTo(".");
$zip->close();
if(!chmod($chromeFilename, 0775)) {
	system("chmod +x $chromeFilename");
}
unlink($chromeFilename . ".zip");

echo "All done!\n";