#!/usr/bin/env php
<?php
/**
 * PHP.Gt (http://php.gt)
 * @copyright Copyright Ⓒ 2014 Bright Flair Ltd. (http://brightflair.com)
 * @license Apache Version 2.0, January 2004. http://www.apache.org/licenses
 */

chdir(__DIR__);
chdir("..");

$seleniumVersion = "2.42.2";
$seleniumFilename = "selenium.jar";
$seleniumRemoteFilename = "selenium-server-standalone-$seleniumVersion.jar";

if(!is_file($seleniumFilename)) {
	file_put_contents($seleniumFilename, fopen(
		"http://selenium-release.storage.googleapis.com/"
		. rtrim($seleniumVersion, ".0"),
		. "/"
		. $seleniumRemoteFilename,
		"r"
	));
}

$bitSize = (PHP_INT_SIZE == 4)
	? 32
	: 64;

$chromeFilename = "chrome-driver"
$chromeVersion = "2.9";
$os = strtolower(php_uname("s"));

if(!is_file($chromeFilename)) {
	file_put_contents($chromeFilename . ".zip", fopen(
		"http://chromedriver.storage.googleapis.com/"
		. $chromeVersion
		. "/"
		. "chromedriver_"
		. $os
		. $bitSize
		. ".zip",
		"r"
	));
}
$zip = new ZipArchive();
$resource = $zip->open($chromeFilename . ".zip");
if(!$resource) {
	echo "Error unzipping chrome driver";
	exit(1);
}
$zip->extractTo($chromeFilename);
$zip->close();
chmod($chromeFilename, 0775);