#!/usr/bin/env php
<?php
/**
 * PHP.Gt (http://php.gt)
 * @copyright Copyright Ⓒ 2014 Bright Flair Ltd. (http://brightflair.com)
 * @license Apache Version 2.0, January 2004. http://www.apache.org/licenses
 */

chdir(__DIR__);
chdir("..");
$exitCode = 0;
system("../vendor/bin/phpunit --colors", $exitCode);
exit($exitCode);