#!/usr/bin/env php
<?php
/**
 * PHP.Gt (http://php.gt)
 * @copyright Copyright Ⓒ 2014 Bright Flair Ltd. (http://brightflair.com)
 * @license Apache Version 2.0, January 2004. http://www.apache.org/licenses
 */

chdir(__DIR__);
$exitCode = 0;
system("../../vendor/bin/phpunit --colors 1>&0", $exitCode);
if($exitCode == 0) {
	echo "\n\nSUCCESS: Unit tests all OK.\n\n";
}
else {
	echo "\n\nERROR: Unit test failed.\n\n";
}
exit($exitCode);