#!/usr/bin/env php
<?php
/**
 * PHP.Gt (http://php.gt)
 * @copyright Copyright Ⓒ 2015 Bright Flair Ltd. (http://brightflair.com)
 * @license http://www.opensource.org/licenses/mit-license.php MIT
 */

chdir(__DIR__);
$exitCode = 0;
system("../../vendor/bin/phpunit --colors 1>&0", $exitCode);
if($exitCode == 0) {
	echo "\n\nSUCCESS: Unit tests all OK.\n\n";
}
else {
	echo "\n\nERROR: Unit test failed.\n\n";
}
exit($exitCode);